### ISSUE TITLE
请问微调后的模型开源了吗，谢谢

### ISSUE THREAD

**Issue by Gpwner** [KongLongGeFDU/TransferTOD#1]

**Comment by KongLongGeFDU** [comment]
我们提供了详细的参数和数据集，按照我们的参数训练一个即可～

**Comment by KongLongGeFDU** [comment]
后续我们会在huggingface上上传模型的权重，但值得一提的是我们的transferTOD-7B采用的基座模型还是baichuan2-7b-base，换成其它更强性能的开源基座模型应该效果会更好。

**Comment by Gpwner** [comment]
> 后续我们会在huggingface上上传模型的权重，但值得一提的是我们的transferTOD-7B采用的基座模型还是baichuan2-7b-base，换成其它更强性能的开源几座模型应该效果会更好。

很高兴看到你们将微调模型开源到了 modelscope,但是我在运行这个模型的时候提示缺少‘adapter_config.json’,麻烦帮忙看看


![image](https://github.com/user-attachments/assets/2edc9426-7ce7-4bb6-a2fb-f766ca6c9ae0)

**Comment by Gpwner** [comment]
请问这个开源的模型不是Lora权重对吗？我这边在运行inference.py的时候不写--lora，是可以成功跑的。但结果没有论文中那么好，请问是什么原因呢 ？
![image](https://github.com/user-attachments/assets/73b55b81-5bce-4b7c-a4ba-abc6c22c8a28)

**Comment by KongLongGeFDU** [comment]
可能是超参数设置的问题？我们可以加个微信进一步讨论。

> 请问这个开源的模型不是Lora权重对吗？我这边在运行inference.py的时候不写--lora，是可以成功跑的。但结果没有论文中那么好，请问是什么原因呢 ？ ![image](https://private-user-images.githubusercontent.com/19349207/378649731-73b55b81-5bce-4b7c-a4ba-abc6c22c8a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NzYzMjMsIm5iZiI6MTcyOTU3NjAyMywicGF0aCI6Ii8xOTM0OTIwNy8zNzg2NDk3MzEtNzNiNTViODEtNWJjZS00YjdjLWE0YmEtYWJjNmMyMmM4YTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA1NDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMDk4MDg4MTkzMzU2NjhlODFhMzgwNmQyY2Y3NmYzZTA4YzMxN2IyZTE5ZTkzOGI4ZDUzM2QwZmU3Yzc5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dex5qde10VKYhUeGVdEU77AvKAXt0La74klRPOzDCJk)

**Comment by KongLongGeFDU** [comment]
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/7be4ab0f-2c6b-4b2d-92cd-61176a228354">

“快递”这一场景在我们论文中测试的结果也并不是很好。

**Comment by Gpwner** [comment]
> 可能是超参数设置的问题？我们可以加个微信进一步讨论。
> 
> > 请问这个开源的模型不是Lora权重对吗？我这边在运行inference.py的时候不写--lora，是可以成功跑的。但结果没有论文中那么好，请问是什么原因呢 ？ ![image](https://private-user-images.githubusercontent.com/19349207/378649731-73b55b81-5bce-4b7c-a4ba-abc6c22c8a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NzYzMjMsIm5iZiI6MTcyOTU3NjAyMywicGF0aCI6Ii8xOTM0OTIwNy8zNzg2NDk3MzEtNzNiNTViODEtNWJjZS00YjdjLWE0YmEtYWJjNmMyMmM4YTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA1NDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMDk4MDg4MTkzMzU2NjhlODFhMzgwNmQyY2Y3NmYzZTA4YzMxN2IyZTE5ZTkzOGI4ZDUzM2QwZmU3Yzc5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dex5qde10VKYhUeGVdEU77AvKAXt0La74klRPOzDCJk)

太好了，您可以留一下微信号吗？或者加我也可以
![b76dde4215534f2c750e5067833bcf9f_qr_code_1729645266228](https://github.com/user-attachments/assets/a8ce82ac-0da9-41a3-9cee-21eb78e54c52)
